GET http://localhost:4000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiUm9uYWxkIE1jRG9uYWxkIiwicGFzc3dvcmQiOiIkMmEkMTAkdHdobjdWdjZ1THpsNTFPYTZkV1MydXg4SlhoT2RIbkJSSDJleXI2LnUwUktodDlQbkQ1REMiLCJpYXQiOjE1ODUxNDQwODksImV4cCI6MTU4NTE0NTg4OX0.jojK4rrurxvZgjSJFWDK8-17IoDcyTtprAUvjUn3FiU
###

POST http://localhost:4000/api/users
Content-Type: application/json

{
    "name": "Ronald McDonald",
    "password": "burger",
    "email": "ron@macca.brg",
    "picture": "https://clown.url"
}

###

DELETE http://localhost:4000/api/users/15

###

POST http://localhost:4000/api/auth/login
Content-Type: application/json

{
    "name": "Ronald McDonald",
    "password": "burger"
}

###

POST http://localhost:4000/api/auth/token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiUm9uYWxkIE1jRG9uYWxkIiwicGFzc3dvcmQiOiIkMmEkMTAkdHdobjdWdjZ1THpsNTFPYTZkV1MydXg4SlhoT2RIbkJSSDJleXI2LnUwUktodDlQbkQ1REMiLCJpYXQiOjE1ODUxNDgzMTR9.kteMbQLqh-RYo2KhWfhFd9w-3iB39B3VGZVh7sdm1K8"
}

###

DELETE http://localhost:4000/api/auth/logout
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiUm9uYWxkIE1jRG9uYWxkIiwicGFzc3dvcmQiOiIkMmEkMTAkdHdobjdWdjZ1THpsNTFPYTZkV1MydXg4SlhoT2RIbkJSSDJleXI2LnUwUktodDlQbkQ1REMiLCJpYXQiOjE1ODUxNDQxMzEsImV4cCI6MTU4NTE0NTkzMX0.UfoPyJYFqYucNxmL8FpHU-_VqpJrK0mlm9KMJuRC1Nc"
}